apiVersion: v1
kind: Namespace
metadata:
  name: service-mesh-benchmark
---
# Fortio Server (Echo Target)
apiVersion: v1
kind: Service
metadata:
  name: fortio-server
  namespace: service-mesh-benchmark
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: fortio-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-server
  namespace: service-mesh-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-server
  template:
    metadata:
      labels:
        app: fortio-server
    spec:
      nodeSelector:
        dedicated: fortio
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "fortio"
          effect: "NoSchedule"
      containers:
      - name: fortio
        image: fortio/fortio
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
# Fortio Client (to run tests manually)
apiVersion: v1
kind: Service
metadata:
  name: fortio-client
  namespace: service-mesh-benchmark
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: fortio-client
---
apiVersion: v1
kind: Pod
metadata:
  name: fortio-client
  namespace: service-mesh-benchmark
  labels:
    app: fortio-client
spec:
  nodeSelector:
    dedicated: fortio
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "fortio"
      effect: "NoSchedule"
  containers:
    - name: fortio
      image: fortio/fortio
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
